### ISSUE TITLE
[Contributors] Add me as Contributor

### ISSUE THREAD

**Issue by larslemos** [mozdevz/Hacktoberfest#1]
Can you please add me as a contributor in the repo. 
Or are we going to show also this during the session?

**Comment by rosariopfernandes** [comment]
I don't think we need to show it during the session. The session should be about forking a repo, cloning it, creating a new branch, editing files, staging, commiting, pushing, making a Pull Request.

Feel free to send a PR with a Contributors.md file with your name on it.
