### ISSUE TITLE
Nomes dos Participantes

### ISSUE THREAD

**Issue by RichaldoElias** [mozdevz/Hacktoberfest#18]
Os nomes dos participantes não estão ordenados.

**Comment by rosariopfernandes** [comment]
Podes enviar um PR para ordená-los. Segue a ordem dos commits. Talvez utilizar uma lista ordenada (1, 2, 3, ...) ao invés de não ordenada (bullet points).

**Comment by Gotaskaen** [comment]
Posso fazer isso

**Comment by rosariopfernandes** [comment]
Visto que @RichaldoElias não deu nenhuma resposta, sure @Gotaskaen go ahead!
